/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get widget configuration
         * @description Returns tenant config, form schema, and available services
         */
        get: operations["getConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Query slot availability
         * @description Returns available time slots based on criteria
         */
        post: operations["checkAvailability"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create new booking
         * @description Creates a booking with automatic conflict detection
         */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get booking details */
        get: operations["getBooking"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update booking status
         * @description Staff endpoint to update booking status
         */
        patch: operations["updateBooking"];
        trace?: never;
    };
    "/forms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List forms for tenant */
        get: operations["listForms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update form schema */
        put: operations["updateForm"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to push notifications */
        post: operations["subscribePush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/push/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send test notification */
        post: operations["testPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cal/venue/{id}.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get venue calendar feed */
        get: operations["getVenueCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cal/resource/{id}.ics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get resource calendar feed */
        get: operations["getResourceCalendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @example BadRequest */
            error: string;
            /** @example Invalid input parameters */
            message: string;
            /** @example 400 */
            statusCode: number;
            details?: {
                field?: string;
                message?: string;
            }[];
        };
        Tenant: {
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /** @example Ristorante Da Luigi */
            name: string;
            /** @example daluigi.booking-saas.com */
            domain: string;
            settings?: {
                /** @example Europe/Rome */
                timezone?: string;
                /** @example EUR */
                currency?: string;
                /** @example it */
                language?: string;
            };
        };
        Service: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @example Cena con Menu Degustazione */
            name: string;
            description?: string;
            /**
             * @description Duration in minutes
             * @example 120
             */
            duration: number;
            capacity?: {
                /** @example 2 */
                min?: number;
                /** @example 8 */
                max?: number;
            };
            /**
             * Format: float
             * @example 75
             */
            price?: number;
            /** @default true */
            active: boolean;
        };
        Venue: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @example Sala Principale */
            name: string;
            address?: {
                street?: string;
                city?: string;
                postalCode?: string;
                country?: string;
            };
            coordinates?: {
                /** Format: double */
                lat?: number;
                /** Format: double */
                lng?: number;
            };
        };
        Resource: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @example Tavolo 5 */
            name: string;
            /** @enum {string} */
            type: "table" | "room" | "equipment" | "staff";
            /** @example 4 */
            capacity?: number;
            /** Format: uuid */
            venueId?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        Slot: {
            /**
             * Format: date-time
             * @example 2025-01-15T19:00:00Z
             */
            start: string;
            /**
             * Format: date-time
             * @example 2025-01-15T21:00:00Z
             */
            end: string;
            /**
             * @description - free: Slot available for booking
             *     - waitlist: Slot full but accepts waitlist
             *     - full: Slot completely unavailable
             * @enum {string}
             */
            status: "free" | "waitlist" | "full";
            /**
             * @description Human-readable explanation for status
             * @example Fully booked
             */
            reason?: string;
            resourceIds?: string[];
            /** Format: float */
            price?: number;
        };
        Booking: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** Format: uuid */
            customerId?: string;
            serviceIds?: string[];
            /** Format: uuid */
            venueId?: string;
            resourceIds?: string[];
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime: string;
            /** @enum {string} */
            status: "pending" | "confirmed" | "arrived" | "completed" | "cancelled" | "no-show";
            /** @example 4 */
            partySize?: number;
            notes?: string;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        Customer: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @example Mario */
            firstName?: string;
            /** @example Rossi */
            lastName?: string;
            /**
             * Format: email
             * @example mario.rossi@example.com
             */
            email?: string;
            /** @example +39 333 1234567 */
            phone?: string;
            /** @description User has consented to data processing */
            gdprConsent?: boolean;
            /** @description User has consented to marketing communications */
            marketingConsent?: boolean;
        };
        Form: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenantId: string;
            /** @example Restaurant Booking Form */
            name?: string;
            description?: string;
            /** @example 1.0.0 */
            schemaVersion: string;
            /** @description Full JSON Schema as per docs/form.schema.json */
            schema?: Record<string, never>;
            /** @default true */
            active: boolean;
        };
        ConfigResponse: {
            tenant: components["schemas"]["Tenant"];
            form: components["schemas"]["Form"];
            services?: components["schemas"]["Service"][];
            venues?: components["schemas"]["Venue"][];
        };
        AvailabilityRequest: {
            /**
             * Format: date
             * @example 2025-01-15
             */
            date: string;
            timeRange?: {
                /**
                 * Format: time
                 * @example 18:00
                 */
                start?: string;
                /**
                 * Format: time
                 * @example 22:00
                 */
                end?: string;
            };
            serviceIds: string[];
            /** Format: uuid */
            venueId?: string;
            /** @example 4 */
            partySize?: number;
            constraints?: {
                [key: string]: unknown;
            };
        };
        AvailabilityResponse: {
            slots?: components["schemas"]["Slot"][];
            meta?: {
                /** Format: date */
                date?: string;
                timezone?: string;
            };
        };
        CreateBookingRequest: {
            /** Format: date-time */
            startTime: string;
            /** Format: date-time */
            endTime?: string;
            serviceIds: string[];
            /** Format: uuid */
            venueId?: string;
            partySize?: number;
            customer: {
                firstName: string;
                lastName?: string;
                /** Format: email */
                email: string;
                phone?: string;
                gdprConsent?: boolean;
                marketingConsent?: boolean;
            };
            notes?: string;
            metadata?: {
                [key: string]: unknown;
            };
        };
        PushSubscription: {
            /** Format: uri */
            endpoint: string;
            keys: {
                p256dh: string;
                auth: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getConfig: {
        parameters: {
            query?: {
                formId?: string;
            };
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configuration retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Tenant or form not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    checkAvailability: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AvailabilityRequest"];
            };
        };
        responses: {
            /** @description Availability results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description Invalid request parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header: {
                "X-Tenant-Id": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "startTime": "2025-01-15T19:00:00Z",
                 *       "endTime": "2025-01-15T21:00:00Z",
                 *       "serviceIds": [
                 *         "550e8400-e29b-41d4-a716-446655440000"
                 *       ],
                 *       "partySize": 4,
                 *       "customer": {
                 *         "firstName": "Mario",
                 *         "lastName": "Rossi",
                 *         "email": "mario.rossi@example.com",
                 *         "phone": "+39 333 1234567",
                 *         "gdprConsent": true,
                 *         "marketingConsent": false
                 *       },
                 *       "notes": "Vegetarian options needed"
                 *     }
                 */
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Booking created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Invalid input or slot not available */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Booking details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "status": "arrived",
                 *       "notes": "Customer checked in"
                 *     }
                 */
                "application/json": {
                    /** @enum {string} */
                    status?: "confirmed" | "arrived" | "completed" | "cancelled" | "no-show";
                    notes?: string;
                };
            };
        };
        responses: {
            /** @description Booking updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Booking not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listForms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of forms */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"][];
                };
            };
        };
    };
    updateForm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Form"];
            };
        };
        responses: {
            /** @description Form updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Form"];
                };
            };
        };
    };
    subscribePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushSubscription"];
            };
        };
        responses: {
            /** @description Subscription created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid subscription */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test notification sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No subscription found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getVenueCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ICS calendar feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
        };
    };
    getResourceCalendar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ICS calendar feed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/calendar": string;
                };
            };
        };
    };
}
